### ISSUE TITLE
Allow "homeshick clone" to specify name for cloned repo?

### ISSUE THREAD

**Issue by tornewuff** [andsens/homeshick#155] opened 2016-06-23 11:48 UTC
Currently if you "homeshick clone" a URL whose basename is the same as a castle you already have (I have more than one repo called "dotfiles" in different places) it simply fails because the target already exists. Maybe there could be some way to specify a name? Regular "git clone" does this with a second parameter but this doesn't work for homeshick which already accepts multiple URLs instead..

**Comment by andsens** [comment] 2016-08-08 19:09
I see the problem. However, the homeshick subcommand arguments have remained stable for quite a long time and while the issue is a valid one I am not going to fix this (i.e. I'm prioritizing stability).

You will have to rename the repos after cloning, sorry :-/

Closing as "won't fix".

**Closed by andsens** 2016-08-08 19:09 UTC
Labels: enhancement
