### ISSUE TITLE
Always says my castles are outdated no matter I just refreshed

### ISSUE THREAD

**Issue by binarykitchen** [andsens/homeshick#190] opened 2019-03-07 23:41 UTC
When I just run `homeshick refresh dotfiles`, confirm with `y` and run it again, it says my dotfiles are outdated uh?

```
michael.heuberger@binarykitchen ~ ❯❯❯ homeshick refresh dotfiles
     outdated dotfiles
     outdated homeshick
      refresh The castles dotfiles,homeshick are outdated.
        pull? [yN] y
         pull dotfiles
         pull homeshick
michael.heuberger@binarykitchen ~ ❯❯❯ homeshick refresh dotfiles
     outdated dotfiles
     outdated homeshick
      refresh The castles dotfiles,homeshick are outdated.
        pull? [yN] y
         pull dotfiles
         pull homeshick
michael.heuberger@binarykitchen ~ ❯❯❯
```

**Comment by binarykitchen** [comment] 2019-03-07 23:47
Also tried with the pull command, same weird result

```
michael.heuberger@binarykitchen ~ ❯❯❯ homeshick pull dotfiles
         pull dotfiles
michael.heuberger@binarykitchen ~ ❯❯❯ homeshick pull dotfiles
         pull dotfiles
michael.heuberger@binarykitchen ~ ❯❯❯ homeshick refresh 1 dotfiles
        fresh dotfiles
michael.heuberger@binarykitchen ~ ❯❯❯ homeshick pull dotfiles
         pull dotfiles
michael.heuberger@binarykitchen ~ ❯❯❯ homeshick refresh 1 dotfiles
        fresh dotfiles
michael.heuberger@binarykitchen ~ ❯❯❯
```

**Comment by andsens** [comment] 2019-03-08 09:17
OK, that is indeed weird. I am unable to reproduce this. In order to diagnose this I need you to test this in a clean environment. Run `test/interactive` in the homeshick folder to get a shell running in a temporary home folder (run `exit` to quit). In that folder run:
```
homeshick clone git@github.com:binarykitchen/dotfiles
homeshick refresh
homeshick refresh
```

Paste a full copy of the results here or link to them in a gist.

**Comment by binarykitchen** [comment] 2019-03-10 21:51
Hmmm, thanks for the suggestions but dont know how to?

> Run test/interactive in the homeshick folder to get a shell running in a temporary home folder

what is `test/interactive`? and which homeshick folder exactly? Tried to find answers myself in your documentation but couldn't find any real examples.

**Comment by andsens** [comment] 2019-10-25 07:29
@binarykitchen, apologies for never getting back to you. I must've missed the notification somehow.
You start `test/interactive` by running `homeshick cd homeshick` to enter the homeshick dir, and then you simply run `test/interactive`. This drops you into a temporary test environment with a clean shell and `$HOME`, everything runs in `/tmp` and is cleaned up once you close the shell.

So when in the test env, clone your dotfiles and try the `refresh` again.

**Comment by andsens** [comment] 2020-05-13 21:38
Closing this, feel free to reopen if you have some more info.

**Closed by andsens** 2020-05-13 21:38 UTC
